In [ ]:
# Template for a program to identify 3 moment of inertia from an XYZ file

# Input name of XYZ file

# Output moment of inertia along the 3 principal axis of rotation: "-- Ia / Ib / Ic"

# Units g.mol^-1.A^2 (within a tolerance of 1*10^-3 g.mol^-1.A^2)

In [ ]:
#Write first any import statements that you need in your program

In [1]:
from numpy import *
from numpy.linalg import *

In [ ]:
# Once 'rcm' is known, subtract 'rcm' from the position of all atoms to obtain coordinates 'rcmα' which have 'rcm' as the origin

rcma = ra - rcm

# rcmα = position of atom a which have rcm as the origin
# ra = position of atom a
# rcm = centre of mass position

In [ ]:
# Build the 3×3 inertia matrix (or inertia tensor) 'I'
# Matrices and vectors are most conveniently implemented as arrays

I = array([[Ixx, Ixy, Ixz],[Iyx, Iyy, Iyz],[Izx, Izy, Izz]])

Ixx = sum(ma * ((ya**2) + (za**2)))
Iyy = sum(ma * ((xa**2) + (za**2)))
Izz = sum(ma * ((xa**2) + (ya**2)))

Ixy = (-1) * sum(ma * xa * ya)
Ixz = (-1) * sum(ma * xa * za)
Iyx = (-1) * sum(ma * ya * xa)
Iyz = (-1) * sum(ma * ya * za)
Izx = (-1) * sum(ma * za * xa)
Izy = (-1) * sum(ma * za * ya)

# ma = mass of atom a
# xa, ya, za = x, y, z coordinates of atom a in 'rcma'

In [ ]:
# The moment of inertia around the principal rotational axes correspond to the eigenvalues of the matrix
# Eigenvalues can be calculated using the functions of the numpy.linalg sub-module
# linalg.eigvals(a) computes eigenvalues of a general matrix

In [335]:
# The file 'hemolysin.xyz' contains the structure of α-Hemolysin
# The file 'H2S.xyz' contains the structure of H2S

In [334]:
def assign_variables(file_name):
    "Assign variables"
    
    # Retrieve file
    stream = open(file_name,'r')
    full_file = list(stream)
    stream.close()
    
    # Assign first line as total mass 'm_total'
    m_total = float(full_file[0])
    
    # Assign file below second line as containing relevant data 'full_file_data'
    full_file_data = full_file[2:]
    
    # Convert string into list where every element is a line 'file_lines'
    file_lines = []
    for lines in range(len((full_file_data))):
        file_lines = file_lines + [full_file_data[lines].split()]
    
    # Make list of atoms in molecule 'atoms_list'
    atoms_list = []
    for lines in range(len((full_file_data))):
        atoms_list = atoms_list + [full_file_data[lines].split()[0]]
        
    # Convert coordinates string into array of floats 'float_coords_array'
    file_coords = []
    for lines in range(len((full_file_data))):
        file_coords = file_coords + [full_file_data[lines].split()[1:]]
    float_coords = []
    for line in file_coords:
        inner_list = []
    for coord in line:
        inner_list = inner_list + [float(coord)]
    float_coords = float_coords + [inner_list]
    float_coords_array = array(float_coords)

In [333]:
# Complete
def parse_line(file_name):
    '''Receives one string (a line of the XYZ file) 
    Returns a list of the form: [element_symbol,coordinate_list]
    e.g.: ['S',[66.52700,-0.24800,33.94300]]'''
    
    assign_variables(file_name)

    # Convert full lines into list
    file_lines = []
    for lines in range(len((full_file_data))):
        file_lines = file_lines + [full_file_data[lines].split()]
    
    # Rearranges list into desired format
    rearranged_list = []
    for lists in file_lines:
        rearranged_list = rearranged_list + [[lists[0]] + [[float(lists[1]),float(lists[2]),float(lists[3])]]]
    return rearranged_list

In [332]:
# Complete
# Atomic mass is obtained in the following way: mass_dictionary[element_symbol_string]
# e.g. mass_dictionary["C"] returns 12.0107
from atomic_masses import *
def get_masses(atoms_list):
    '''Receives one list containing strings with chemical symbols, 
    Returns a 1D array with the atomic masses for each element in the original list'''
    atomic_masses = []
    for symbol in atoms_list:
        atomic_masses = atomic_masses + [mass_dictionary[symbol]]
    return array(atomic_masses)

In [355]:
# Test cm_position
print(atoms_list)
get_masses(atoms_list)

['S', 'H', 'H']


array([32.065  ,  1.00794,  1.00794])

In [356]:
# Test cm_position
float_coords_array

array([[ 0.      ,  0.      ,  0.102249],
       [ 0.      ,  0.968059, -0.817992],
       [ 0.      , -0.968059, -0.817992]])

In [366]:
temp = 0
for ma in get_masses(atoms_list):
    print(ma)
    temp = temp + ma * float_coords_array
temp

32.065
1.00794
1.00794


array([[  0.        ,   0.        ,   3.4847359 ],
       [  0.        ,  32.99230261, -27.87788719],
       [  0.        , -32.99230261, -27.87788719]])

In [ ]:
# rcm = centre of mass position
# m_total = total mass of molecule
# ma = mass of atom a
# ra = position of atom a
def cm_position(array1, array2):
    '''Receives two arrays of numbers: 
    array1 is a 1D array with mass data
    array2 is a 2D array where each row contains position data 
    Returns a 1D array with the position of the centre of mass 'rcm' '''
    
    
    rcm = (1 / m_total) * sum(ma * ra)

In [336]:
# Complete
def buildi(coords_array):
    '''Receives a 1D array with the coordinates of one atom, array([x,y,z])
    Returns a 3×3 array corresponding to a matrix of the form:
    array([[((y**2)+(z**2)) , ((-1)*x*y) , ((-1)*x*z)],
    [((-1)*x*y) , ((x**2)+(z**2)) , ((-1)*y*z)],
    [((-1)*x*z) , ((-1)*y*z) , ((x**2)+(y**2))]])'''
    x = coords_array[0]
    y = coords_array[1]
    z = coords_array[2]
    return array([[((y**2)+(z**2)) , ((-1)*x*y) , ((-1)*x*z)],
    [((-1)*x*y) , ((x**2)+(z**2)) , ((-1)*y*z)],
    [((-1)*x*z) , ((-1)*y*z) , ((x**2)+(y**2))]])

In [ ]:
def inertia_matrix(array1,array2):
    '''Receives two arrays of numbers:
    array1 is a 1D array with mass data
    array2 is a 2D array where each row contains position data
    Return a 3×3 array corresponding to the inertia matrix'''
    pass

In [ ]:
#The following if statement does not affect the working of the program,
#but will allow to test your functions even if the rest of the program
#does not work

if __name__=="__main__":

    #Remove the pass statement below and write the rest of the
    #program inside this if block
    #Do not forget indentation

    pass